/**
 * Property-Based Tests for OllamaClient
 *
 * **Feature: social-copilot-v2, Property 21: Ollama Request Configuration**
 * **Validates: Requirements 9.3, 9.4**
 *
 * Property 21: *For any* Ollama API call, the request should include keep_alive: -1,
 * and Intent Analyst calls should use temperature: 0.1.
 */
import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'
import { OllamaClient } from '../../services/ollama-client'

// Arbitrary generator for valid prompt strings (non-empty)
const promptArbitrary = fc.string({ minLength: 1, maxLength: 500 })

// Arbitrary generator for optional system prompt
const systemPromptArbitrary = fc.option(fc.string({ minLength: 1, maxLength: 500 }), {
  nil: undefined
})

// Arbitrary generator for temperature values (0.0 to 2.0)
const temperatureArbitrary = fc.float({ min: 0, max: 2, noNaN: true })

describe('Property 21: Ollama Request Configuration', () => {
  /**
   * **Feature: social-copilot-v2, Property 21: Ollama Request Configuration**
   * **Validates: Requirements 9.3**
   *
   * *For any* Ollama API request generated by the system, it SHALL include
   * keep_alive set to -1 to maintain model in memory.
   */
  it('should always set keep_alive to -1 for all requests', () => {
    fc.assert(
      fc.property(
        promptArbitrary,
        systemPromptArbitrary,
        temperatureArbitrary,
        (prompt: string, system: string | undefined, temperature: number) => {
          const client = new OllamaClient()
          const request = client.buildRequest({ prompt, system, temperature })

          // Requirement 9.3: keep_alive must be -1
          expect(request.keep_alive).toBe(-1)
        }
      ),
      { numRuns: 100 }
    )
  })

  /**
   * **Feature: social-copilot-v2, Property 21: Ollama Request Configuration**
   * **Validates: Requirements 9.4**
   *
   * *For any* Intent Agent request, it SHALL use temperature 0.1 for stable results.
   */
  it('should set temperature to 0.1 for Intent Agent requests', () => {
    fc.assert(
      fc.property(
        promptArbitrary,
        systemPromptArbitrary,
        (prompt: string, system: string | undefined) => {
          const client = new OllamaClient()
          const request = client.buildIntentAgentRequest(prompt, system)

          // Requirement 9.4: Intent Agent uses temperature 0.1
          expect(request.temperature).toBe(0.1)
          // Also verify keep_alive is still -1 (Requirement 9.3)
          expect(request.keep_alive).toBe(-1)
        }
      ),
      { numRuns: 100 }
    )
  })

  /**
   * **Feature: social-copilot-v2, Property 21: Ollama Request Configuration**
   * **Validates: Requirements 9.3**
   *
   * *For any* request built with custom configuration, keep_alive should
   * still default to -1 unless explicitly overridden in config.
   */
  it('should preserve keep_alive=-1 with custom model configuration', () => {
    fc.assert(
      fc.property(
        promptArbitrary,
        fc.string({ minLength: 1, maxLength: 50 }).filter((s) => s.trim().length > 0),
        (prompt: string, customModel: string) => {
          const client = new OllamaClient({ model: customModel })
          const request = client.buildRequest({ prompt })

          // keep_alive should still be -1 regardless of model
          expect(request.keep_alive).toBe(-1)
          // Model should be the custom one
          expect(request.model).toBe(customModel)
        }
      ),
      { numRuns: 100 }
    )
  })

  /**
   * **Feature: social-copilot-v2, Property 21: Ollama Request Configuration**
   * **Validates: Requirements 9.3, 9.4**
   *
   * *For any* request, the model field should be populated from config
   * and stream should be false for non-streaming responses.
   */
  it('should include model from config and disable streaming', () => {
    fc.assert(
      fc.property(promptArbitrary, (prompt: string) => {
        const client = new OllamaClient()
        const request = client.buildRequest({ prompt })

        // Model should be set from default config
        expect(request.model).toBe('qwen3:8b')
        // Stream should be false
        expect(request.stream).toBe(false)
      }),
      { numRuns: 100 }
    )
  })

  /**
   * **Feature: social-copilot-v2, Property 21: Ollama Request Configuration**
   * **Validates: Requirements 9.3**
   *
   * *For any* Coach Agent request, keep_alive should be -1 and temperature
   * should be set for creative suggestions.
   */
  it('should configure Coach Agent requests with appropriate temperature', () => {
    fc.assert(
      fc.property(
        promptArbitrary,
        systemPromptArbitrary,
        (prompt: string, system: string | undefined) => {
          const client = new OllamaClient()
          const request = client.buildCoachAgentRequest(prompt, system)

          // keep_alive must be -1 (Requirement 9.3)
          expect(request.keep_alive).toBe(-1)
          // Coach Agent uses higher temperature for creativity
          expect(request.temperature).toBe(0.7)
        }
      ),
      { numRuns: 100 }
    )
  })
})
